/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceace;

/**
 *
 * @author Jonathon
 */
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
        setSize(ScreenDimensions.width, ScreenDimensions.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreditsLabel = new javax.swing.JLabel();
        PrgrammingLabel = new javax.swing.JLabel();
        ArtLabel = new javax.swing.JLabel();
        SoundLabel = new javax.swing.JLabel();
        MusicLabel = new javax.swing.JLabel();
        ReturnToMainMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2048, 1024));

        CreditsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CreditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreditsLabel.setText("Credits");

        PrgrammingLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PrgrammingLabel.setText("Programming: Jonathon D. Madore");

        ArtLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ArtLabel.setText("Art:");

        SoundLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SoundLabel.setText("Sound:");

        MusicLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MusicLabel.setText("Music:");

        ReturnToMainMenuButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ReturnToMainMenuButton.setText("Return to Main Menu");
        ReturnToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnToMainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(700, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReturnToMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addComponent(CreditsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addComponent(PrgrammingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addComponent(ArtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addComponent(SoundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addComponent(MusicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
                .addGap(700, 700, 700))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ArtLabel, CreditsLabel, MusicLabel, PrgrammingLabel, ReturnToMainMenuButton, SoundLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(CreditsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(PrgrammingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(ArtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(SoundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(MusicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(ReturnToMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ArtLabel, CreditsLabel, MusicLabel, PrgrammingLabel, ReturnToMainMenuButton, SoundLabel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnToMainMenuButtonActionPerformed
        GameStates gs = GameStates.MENU;
        Menu menu = new Menu(gs);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_ReturnToMainMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArtLabel;
    private javax.swing.JLabel CreditsLabel;
    private javax.swing.JLabel MusicLabel;
    private javax.swing.JLabel PrgrammingLabel;
    private javax.swing.JButton ReturnToMainMenuButton;
    private javax.swing.JLabel SoundLabel;
    // End of variables declaration//GEN-END:variables
}
